# Generated by Django 6.0.6 on 2026-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('reviewer', 'Reviewer'), ('member_secretary', 'Member Secretary'), ('chairperson', 'Chairperson')], default='student', max_length=30),
        ),
    ]
